version: '2.1'
services:
  database:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:12.5-alpine
    restart: always
    ports:
      - 7777:5432